function normalizeSetListHeaderTemplate(text) {
  const raw = String(text || "").replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  const trimmed = raw.replace(/\s+$/, "");
  if (!trimmed) return "";
  return `${trimmed}\n`;
}

function getSetListFileHeaderText(setListHeaderText) {
  const tpl = normalizeSetListHeaderTemplate(setListHeaderText);
  if (!tpl) return "";
  return `% Generated by ABCarus Set List\n${tpl}`;
}

function getPrintableSetListItems(items) {
  return Array.isArray(items)
    ? items.filter((item) => item && (!item.export || item.export.includeInPdf !== false))
    : [];
}

function shouldInjectNewPageBeforeTune(tuneText, { mode, idx, pageBreakBefore = false }) {
  if (idx <= 0) return false;
  if (pageBreakBefore) return true;
  if (mode === "none") return false;
  if (mode === "perTune") return true;
  if (mode !== "auto") return false;
  const text = String(tuneText || "");
  const lines = text.split(/\r\n|\n|\r/);
  const nonEmpty = [];
  for (let i = 0; i < lines.length; i++) {
    const l = String(lines[i] || "").trim();
    if (!l) continue;
    nonEmpty.push(l);
    if (nonEmpty.length >= 3) break;
  }
  if (nonEmpty.some((l) => l.startsWith("%%newpage"))) return false;
  const lineCount = lines.length;
  const long = lineCount >= 80 || text.length >= 5000;
  return long;
}

function buildSetListExportAbc({
  items,
  headerText,
  pageBreaks,
  ensureXNumberInAbc,
  appendTuneToContent,
} = {}) {
  if (!Array.isArray(items) || items.length === 0) return "";
  const renumber = typeof ensureXNumberInAbc === "function"
    ? ensureXNumberInAbc
    : (text) => text;
  const appendTune = typeof appendTuneToContent === "function"
    ? appendTuneToContent
    : (content, tune) => `${content || ""}${tune || ""}`;

  let out = "";
  const fileHeader = getSetListFileHeaderText(headerText);
  if (fileHeader.trim()) out = `${fileHeader}\n`;

  let writtenCount = 0;
  for (let i = 0; i < items.length; i++) {
    const item = items[i] || {};
    const raw = String(item.text || "");
    if (!raw.trim()) continue;

    let tune = raw;
    const inject = shouldInjectNewPageBeforeTune(tune, {
      mode: pageBreaks,
      idx: writtenCount,
      pageBreakBefore: Boolean(item.export && item.export.pageBreakBefore),
    });
    if (inject) tune = `%%newpage\n${tune}`;

    tune = renumber(tune, writtenCount + 1);
    out = appendTune(out, tune);
    writtenCount += 1;
  }
  return out;
}

export {
  buildSetListExportAbc,
  getPrintableSetListItems,
  getSetListFileHeaderText,
  normalizeSetListHeaderTemplate,
  shouldInjectNewPageBeforeTune,
};
