function getPlatformDefaults() {
  return {
    // On Cinnamon/GTK, native file dialogs can appear off-screen; portal dialogs are more reliable.
    usePortalFileDialogs: process.platform === "linux",
  };
}

function getSettingsSchema() {
  const platformDefaults = getPlatformDefaults();
  return [
    // UI layout (renderer-managed). These keys are persisted and exportable, but intentionally have no Settings UI controls.
    { key: "layoutSplitOrientation", type: "string", default: "vertical" },
    { key: "layoutSplitRatioVertical", type: "number", default: 0.5 },
    { key: "layoutSplitRatioHorizontal", type: "number", default: 0.5 },
    { key: "layoutRenderZoomVertical", type: "number", default: 1 },
    { key: "layoutRenderZoomHorizontal", type: "number", default: 1 },
    {
      key: "renderZoom",
      type: "number",
      default: 1,
      section: "General",
      group: "Zoom",
      groupOrder: 10,
      label: "Score zoom (%)",
      help: "Zoom level for the rendered score (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "editorZoom",
      type: "number",
      default: 1,
      section: "General",
      group: "Zoom",
      groupOrder: 10,
      label: "Editor zoom (%)",
      help: "Zoom level for the editor (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "followPlayback",
      type: "boolean",
      default: true,
      section: "Playback",
      label: "Follow playback",
      help: "Controls the Follow toggle in the toolbar.",
      // UI control lives in the main toolbar, not in the Settings modal.
    },
    {
      key: "playbackLoopEnabled",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop playback (Focus)",
      help: "When enabled, loops playback between the specified measure numbers in Focus mode.",
      ui: { input: "checkbox" },
    },
    {
      key: "playbackLoopFromMeasure",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop from measure",
      help: "Start measure number (1-based). Use 0 to start from the first playable bar.",
      ui: { input: "number", min: 0, max: 100000, step: 1 },
      advanced: true,
    },
    {
      key: "playbackLoopToMeasure",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop to measure",
      help: "End measure number (inclusive, 1-based). Use 0 to loop to the end of the tune.",
      ui: { input: "number", min: 0, max: 100000, step: 1 },
      advanced: true,
    },
    {
      key: "followHighlightColor",
      type: "string",
      default: "#1e90ff",
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Highlight color",
      help: "Color used for playback highlights and the playhead.",
      ui: { input: "color" },
    },
    {
      key: "followMeasureColor",
      type: "string",
      default: "",
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Staff highlight color",
      help: "Optional override for staff highlighting (leave empty to use Highlight color).",
      ui: { input: "color" },
      advanced: true,
    },
    {
      key: "followHighlightBarOpacity",
      type: "number",
      default: 0.12,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Bar highlight opacity (%)",
      help: "Opacity for the current bar highlight in the score (0–60%).",
      ui: { input: "percent", min: 0, max: 60, step: 1 },
    },
    {
      key: "followMeasureOpacity",
      type: "number",
      default: 0.08,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Staff highlight opacity (%)",
      help: "Opacity for the current staff highlight during playback (0–30%).",
      ui: { input: "percent", min: 0, max: 30, step: 1 },
    },
    {
      key: "followPlayheadOpacity",
      type: "number",
      default: 0.7,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Playhead opacity (%)",
      help: "Opacity for the vertical playhead line in the score (0–100%).",
      ui: { input: "percent", min: 0, max: 100, step: 1 },
    },
    {
      key: "followPlayheadWidth",
      type: "number",
      default: 2,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Playhead width (px)",
      help: "Thickness of the vertical playhead line in the score (1–6px).",
      ui: { input: "number", min: 1, max: 6, step: 1 },
    },
    {
      key: "followPlayheadPad",
      type: "number",
      default: 8,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Playhead extra height (px)",
      help: "Extends the playhead line slightly above/below the staff (0–24px).",
      ui: { input: "number", min: 0, max: 24, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadBetweenNotesWeight",
      type: "number",
      default: 1,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Between-notes position (%)",
      help: "100% = between previous and current note; 0% = on the current note.",
      ui: { input: "percent", min: 0, max: 100, step: 5 },
      advanced: true,
    },
    {
      key: "playbackNativeMidiDrums",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Use native abc2svg %%MIDI drum* (experimental)",
      help: "Experimental: try using abc2svg's native %%MIDI drum/drumon/drumoff/drumbars support instead of ABCarus's injected V:DRUM voice. May affect playback mapping in edge cases.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "followPlayheadShift",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Playhead horizontal shift (px)",
      help: "Negative values move the playhead left; positive move it right (-20…20).",
      ui: { input: "number", min: -20, max: 20, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadFirstBias",
      type: "number",
      default: 6,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "First-note bias (px)",
      help: "When there is no previous note to interpolate from, bias the playhead slightly left (0–20).",
      ui: { input: "number", min: 0, max: 20, step: 1 },
      advanced: true,
    },
	    {
	      key: "playbackAutoScrollMode",
	      type: "string",
	      default: "Keep Visible",
	      section: "Playback",
	      group: "Auto-scroll",
	      groupOrder: 10,
	      label: "Auto-scroll mode",
	      help: "Keeps the playhead visible while playing, scrolling the score automatically.",
	      ui: {
	        input: "select",
	        options: [
	          { value: "Off", label: "Off" },
	          { value: "Keep Visible", label: "Keep Cursor Visible" },
	          { value: "Page Turn", label: "Smooth Follow" },
	          { value: "Centered", label: "Center Cursor" },
	        ],
	      },
	    },
    {
      key: "playbackAutoScrollHorizontal",
      type: "boolean",
      default: true,
      section: "Playback",
      group: "Auto-scroll",
      groupOrder: 10,
      label: "Allow horizontal auto-scroll",
      help: "When needed (high zoom), also scroll horizontally to keep the playhead visible.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackAutoScrollPauseMs",
      type: "number",
      default: 1800,
      section: "Playback",
      group: "Auto-scroll",
      groupOrder: 10,
      label: "Auto-scroll pause after manual scroll (ms)",
      help: "Temporarily pauses auto-scroll after the user scrolls manually (0–5000ms).",
      ui: { input: "number", min: 0, max: 5000, step: 100 },
      advanced: true,
    },
    {
      key: "soundfontName",
      type: "string",
      default: "TimGM6mb.sf2",
      section: "Fonts",
      group: "Score",
      groupOrder: 10,
      label: "Soundfont (SF2)",
      help: "Default soundfont for playback.",
      ui: { input: "select", options: "soundfonts" },
    },
    {
      key: "drumVelocityMap",
      type: "object",
      default: {},
      section: "Drums",
      label: "Drum mixer",
      help: "Default velocities for GM drum pitches. Tune-specific velocities still apply.",
      ui: { input: "drumVelocityMap" },
      advanced: true,
    },
    {
      key: "useNativeTranspose",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "Transpose",
      groupOrder: 10,
      label: "Use native transpose",
      help: "When enabled, semitone transposition runs via the built-in JS engine.",
      ui: { input: "checkbox" },
    },
    {
      key: "autoAlignBarsAfterTransforms",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "Formatting",
      groupOrder: 30,
      label: "Auto-align bars after transforms",
      help: "After running a transform, optionally align bar spacing for readability.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "abc2xmlArgs",
      type: "string",
      default: "",
      section: "Tools",
      group: "Import/Export",
      groupOrder: 20,
      label: "abc2xml flags",
      help: "Space-separated flags passed to abc2xml.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "xml2abcArgs",
      type: "string",
      default: "",
      section: "Tools",
      group: "Import/Export",
      groupOrder: 20,
      label: "xml2abc flags",
      help: "Space-separated flags passed to xml2abc.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "globalHeaderEnabled",
      type: "boolean",
      default: true,
      section: "Header",
      group: "Global header",
      groupOrder: 10,
      label: "Enable global header",
      help: "Prepended before file headers and tunes during render/playback.",
      ui: { input: "checkbox" },
    },
    {
      key: "globalHeaderText",
      type: "string",
      default: "",
      section: "Header",
      group: "Global header",
      groupOrder: 10,
      label: "Global header text",
      help: "Prepended before file headers and tunes during render/playback.",
      ui: { input: "code" },
    },
    {
      key: "abc2svgNotationFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      group: "Score",
      groupOrder: 10,
      label: "Notation font",
      help: "Optional SMuFL notation font override for abc2svg (%%musicfont).",
      ui: { input: "select", options: "notationFonts" },
    },
    {
      key: "abc2svgTextFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      group: "Score",
      groupOrder: 10,
      label: "Text font",
      help: "Optional text font override for abc2svg titles/labels.",
      ui: { input: "select", options: "textFonts" },
    },
    {
      key: "uiFontFamily",
      type: "string",
      default: "",
      section: "Fonts",
      group: "UI",
      groupOrder: 5,
      label: "UI font family",
      help: "CSS font-family used for the app UI (does not affect the OS menu bar).",
      ui: { input: "text", placeholder: "system-ui, -apple-system, \"Segoe UI\", Roboto, Ubuntu, Cantarell, \"Noto Sans\", sans-serif" },
    },
    {
      key: "uiFontSize",
      type: "number",
      default: 13,
      section: "Fonts",
      group: "UI",
      groupOrder: 5,
      label: "UI font size",
      help: "Font size for the app UI (px).",
      ui: { input: "number", min: 10, max: 28, step: 1 },
    },
    {
      key: "printAllPageBreaks",
      type: "string",
      default: "perTune",
      section: "Print",
      group: "All tunes",
      groupOrder: 10,
      label: "Print All: page breaks",
      help: "Per tune prints each tune on a separate page. Continuous prints tunes back-to-back; use %%newpage in ABC to force page breaks.",
      ui: {
        input: "select",
        options: [
          { value: "perTune", label: "Per tune" },
          { value: "continuous", label: "Continuous (use %%newpage)" },
        ],
      },
    },
    {
      key: "printAllAskEachTime",
      type: "boolean",
      default: true,
      section: "Print",
      group: "All tunes",
      groupOrder: 10,
      label: "Ask before Print All",
      help: "When enabled, shows the Print All options dialog each time.",
      ui: { input: "checkbox" },
    },
    {
      key: "editorFontFamily",
      type: "string",
      default: "\"ABCarus Noto Sans Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Font family",
      help: "Font used in the ABC editor.",
      ui: { input: "select", options: [] },
    },
    {
      key: "editorFontSize",
      type: "number",
      default: 13,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Font size",
      help: "Font size used in the ABC editor.",
      ui: { input: "number", min: 8, max: 32, step: 1 },
    },
    {
      key: "editorNotesBold",
      type: "boolean",
      default: true,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Bold notes",
      help: "Renders ABC note letters in bold in the editor.",
      ui: { input: "checkbox" },
    },
    {
      key: "editorLyricsBold",
      type: "boolean",
      default: true,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Bold inline lyrics",
      help: "Renders inline lyrics (w:) in bold in the editor.",
      ui: { input: "checkbox" },
    },
    {
      key: "usePortalFileDialogs",
      type: "boolean",
      default: platformDefaults.usePortalFileDialogs,
      section: "Dialogs",
      group: "File dialogs",
      groupOrder: 10,
      label: "Use portal file dialogs (Linux)",
      help: "Improves Open/Save dialog placement on some Linux desktops.",
      ui: { input: "checkbox" },
    },
    {
      key: "confirmAppendToActiveFile",
      type: "boolean",
      default: true,
      section: "Dialogs",
      group: "Confirmations",
      groupOrder: 20,
      label: "Confirm append to active file",
      help: "When enabled, shows a confirmation dialog before appending (e.g., after moving/copying a tune into the active file).",
      ui: { input: "checkbox" },
    },
    {
      key: "libraryAutoRenumberAfterMove",
      type: "boolean",
      default: false,
      section: "Library",
      group: "Behavior",
      groupOrder: 10,
      label: "Auto-renumber X after move",
      help: "When moving a tune between files, renumber X headers in both files to be sequential (starting at the first X).",
      ui: { input: "checkbox" },
    },
    {
      key: "templatesFolder",
      type: "string",
      default: "",
      section: "Library",
      group: "Templates",
      groupOrder: 20,
      label: "Templates folder",
      help: "Optional folder with .abc files used as tune templates. If empty, ABCarus uses its default templates folder under user data.",
      ui: { input: "text" },
    },
    // Non-modal / internal / persisted UI prefs (kept for compatibility).
    { key: "soundfontPaths", type: "array", default: [], section: "Advanced", advanced: true, legacy: true },
    { key: "disclaimerSeen", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "errorsEnabled", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "usePortalFileDialogsSetByUser", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneVisible", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneWidth", type: "number", default: 280, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryGroupBy", type: "string", default: "file", section: "Advanced", advanced: true, legacy: true },
    { key: "librarySortBy", type: "string", default: "update_desc", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryFilterText", type: "string", default: "", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryUiStateByRoot", type: "object", default: {}, section: "Advanced", advanced: true, legacy: true },
  ];
}

function getDefaultSettingsFromSchema(schema) {
  const out = {};
  for (const entry of schema) {
    if (!entry || !entry.key) continue;
    out[entry.key] = entry.default;
  }
  return out;
}

function getDefaultSettings() {
  return getDefaultSettingsFromSchema(getSettingsSchema());
}

module.exports = {
  getSettingsSchema,
  getDefaultSettings,
};
