function getPlatformDefaults() {
  return {
    // On Cinnamon/GTK, native file dialogs can appear off-screen; portal dialogs are more reliable.
    usePortalFileDialogs: process.platform === "linux",
  };
}

function getSettingsSchema() {
  const platformDefaults = getPlatformDefaults();
  return [
    // UI layout (renderer-managed). These keys are persisted and exportable, but intentionally have no Settings UI controls.
    { key: "layoutSplitOrientation", type: "string", default: "vertical" },
    { key: "layoutSplitRatioVertical", type: "number", default: 0.5 },
    { key: "layoutSplitRatioHorizontal", type: "number", default: 0.5 },
    { key: "layoutRenderZoomVertical", type: "number", default: 1 },
    { key: "layoutRenderZoomHorizontal", type: "number", default: 1 },
    {
      key: "renderZoom",
      type: "number",
      default: 1,
      section: "General",
      group: "Zoom",
      groupOrder: 10,
      label: "Score zoom (%)",
      help: "Zoom level for the rendered score (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "editorZoom",
      type: "number",
      default: 1,
      section: "General",
      group: "Zoom",
      groupOrder: 10,
      label: "Editor zoom (%)",
      help: "Zoom level for the editor (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "startupSplashSeconds",
      type: "number",
      default: 0,
      section: "General",
      group: "Startup",
      groupOrder: 12,
      label: "Startup splash duration (s)",
      help: "Minimum time to keep the startup splash visible. Set 0 to disable splash.",
      ui: { input: "number", min: 0, max: 30, step: 1 },
    },
    {
      key: "followPlayback",
      type: "boolean",
      default: true,
      section: "Playback",
      label: "Follow playback",
      help: "Controls the Follow toggle in the toolbar.",
      // UI control lives in the main toolbar, not in the Settings modal.
    },
    {
      key: "playbackLoopEnabled",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop playback (Focus)",
      help: "When enabled, loops playback between the specified measure numbers in Focus mode.",
      ui: { input: "checkbox" },
    },
    {
      key: "playbackLoopFromMeasure",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop from measure",
      help: "Start measure number (1-based). Use 0 to start from the first playable bar.",
      ui: { input: "number", min: 0, max: 100000, step: 1 },
      advanced: true,
    },
    {
      key: "playbackLoopToMeasure",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Loop",
      groupOrder: 30,
      label: "Loop to measure",
      help: "End measure number (inclusive, 1-based). Use 0 to loop to the end of the tune.",
      ui: { input: "number", min: 0, max: 100000, step: 1 },
      advanced: true,
    },
    {
      key: "playbackSelectionLoopEnabled",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Selection",
      groupOrder: 35,
      label: "Loop selection",
      help: "When enabled, playback will loop the current selection instead of playing it once.",
      ui: { input: "checkbox" },
    },
    {
      key: "playbackSelectionSuppressRepeats",
      type: "boolean",
      default: true,
      section: "Playback",
      group: "Selection",
      groupOrder: 35,
      label: "Selection: suppress repeats",
      help: "When enabled, repeats inside the selected range are flattened for playback.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackSelectionMuteGchords",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Selection",
      groupOrder: 35,
      label: "Selection: mute chord symbols",
      help: "When enabled, chord symbols are muted during selection playback.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackSelectionAllowMidiDrums",
      type: "boolean",
      default: false,
      section: "Playback",
      group: "Selection",
      groupOrder: 35,
      label: "Selection: allow MIDI drums",
      help: "Best-effort. When enabled, selection playback keeps %%MIDI drum* directives. This may be unstable with short ranges or repeats.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackSelectionMutedVoices",
      type: "string",
      default: "",
      section: "Playback",
      group: "Selection",
      groupOrder: 35,
      label: "Selection: muted voices",
      help: "Comma-separated voice IDs to mute during selection playback. Voice 1 is always treated as the de-facto first voice. Best-effort; inline [V:...] switches are not supported.",
      ui: { input: "text" },
      advanced: true,
    },
    {
      key: "followHighlightColor",
      type: "string",
      default: "#1e90ff",
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Highlight color",
      help: "Color used for playback highlights and the playhead.",
      ui: { input: "color" },
    },
    {
      key: "followMeasureColor",
      type: "string",
      default: "",
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Staff highlight color",
      help: "Optional override for staff highlighting (leave empty to use Highlight color).",
      ui: { input: "color" },
      advanced: true,
    },
    {
      key: "followHighlightBarOpacity",
      type: "number",
      default: 0.12,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Bar highlight opacity (%)",
      help: "Opacity for the current bar highlight in the score (0–60%).",
      ui: { input: "percent", min: 0, max: 60, step: 1 },
    },
    {
      key: "followMeasureOpacity",
      type: "number",
      default: 0.08,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Staff highlight opacity (%)",
      help: "Opacity for the current staff highlight during playback (0–30%).",
      ui: { input: "percent", min: 0, max: 30, step: 1 },
    },
    {
      key: "followPlayheadOpacity",
      type: "number",
      default: 0.7,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Playhead opacity (%)",
      help: "Opacity for the vertical playhead line in the score (0–100%).",
      ui: { input: "percent", min: 0, max: 100, step: 1 },
    },
    {
      key: "followPlayheadWidth",
      type: "number",
      default: 2,
      section: "Playback",
      group: "Visual",
      groupOrder: 40,
      label: "Playhead width (px)",
      help: "Thickness of the vertical playhead line in the score (1–6px).",
      ui: { input: "number", min: 1, max: 6, step: 1 },
    },
    {
      key: "followPlayheadPad",
      type: "number",
      default: 8,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Playhead extra height (px)",
      help: "Extends the playhead line slightly above/below the staff (0–24px).",
      ui: { input: "number", min: 0, max: 24, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadBetweenNotesWeight",
      type: "number",
      default: 1,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Between-notes position (%)",
      help: "100% = between previous and current note; 0% = on the current note.",
      ui: { input: "percent", min: 0, max: 100, step: 5 },
      advanced: true,
    },
    {
      key: "followPlayheadShift",
      type: "number",
      default: 0,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "Playhead horizontal shift (px)",
      help: "Negative values move the playhead left; positive move it right (-20…20).",
      ui: { input: "number", min: -20, max: 20, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadFirstBias",
      type: "number",
      default: 6,
      section: "Playback",
      group: "Follow",
      groupOrder: 20,
      label: "First-note bias (px)",
      help: "When there is no previous note to interpolate from, bias the playhead slightly left (0–20).",
      ui: { input: "number", min: 0, max: 20, step: 1 },
      advanced: true,
    },
	    {
	      key: "playbackAutoScrollMode",
	      type: "string",
	      default: "Keep Visible",
	      section: "Playback",
	      group: "Auto-scroll",
	      groupOrder: 10,
	      label: "Auto-scroll mode",
	      help: "Keeps the playhead visible while playing, scrolling the score automatically.",
	      ui: {
	        input: "select",
	        options: [
	          { value: "Off", label: "Off" },
	          { value: "Keep Visible", label: "Keep Cursor Visible" },
	          { value: "Page Turn", label: "Smooth Follow" },
	          { value: "Centered", label: "Center Cursor" },
	        ],
	      },
	    },
    {
      key: "playbackAutoScrollHorizontal",
      type: "boolean",
      default: true,
      section: "Playback",
      group: "Auto-scroll",
      groupOrder: 10,
      label: "Allow horizontal auto-scroll",
      help: "When needed (high zoom), also scroll horizontally to keep the playhead visible.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackAutoScrollPauseMs",
      type: "number",
      default: 1800,
      section: "Playback",
      group: "Auto-scroll",
      groupOrder: 10,
      label: "Auto-scroll pause after manual scroll (ms)",
      help: "Temporarily pauses auto-scroll after the user scrolls manually (0–5000ms).",
      ui: { input: "number", min: 0, max: 5000, step: 100 },
      advanced: true,
    },
    {
      key: "soundfontName",
      type: "string",
      default: "TimGM6mb.sf2",
      section: "Fonts",
      group: "Notation",
      groupOrder: 10,
      label: "Soundfont (SF2)",
      help: "Default soundfont for playback.",
      ui: { input: "select", options: "soundfonts" },
    },
    {
      key: "drumVelocityMap",
      type: "object",
      default: {},
      section: "Drums",
      label: "Drum mixer",
      help: "Default velocities for GM drum pitches. Tune-specific velocities still apply.",
      ui: { input: "drumVelocityMap" },
      advanced: true,
    },
    {
      key: "useNativeTranspose",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "Transpose",
      groupOrder: 10,
      label: "Use native transpose",
      help: "When enabled, semitone transposition runs via the built-in JS engine.",
      ui: { input: "checkbox" },
    },
    {
      key: "editorHelpEnabled",
      type: "boolean",
      default: true,
      section: "General",
      group: "Editor Help",
      groupOrder: 30,
      label: "Enable editor help",
      help: "Shows editor assistance (e.g., completion suggestions and hover help).",
      ui: { input: "checkbox" },
    },
    {
      key: "supportMicrotonalNotation",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "Microtonal notation",
      groupOrder: 5,
      label: "Support microtonal notation",
      help: "Enables optional makam/perde/EDO-53 tools such as Intonation Explorer and Makam DNA. Disabled by default for most users.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "payloadModeEnabled",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "Diagnostics",
      groupOrder: 6,
      label: "Enable Payload Mode (Diagnostics)",
      help: "Enables Payload Mode under Help → Diagnostics. Disabled by default for most users.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    // Back-compat: older builds used different names for microtonal tools.
    { key: "makamToolsEnabled", type: "boolean", default: false, section: "Tools", advanced: true, legacy: true },
    { key: "studyToolsEnabled", type: "boolean", default: false, section: "Tools", advanced: true, legacy: true },
    {
      key: "autoAlignBarsAfterTransforms",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "Formatting",
      groupOrder: 30,
      label: "Auto-align bars after transforms",
      help: "After running a transform, optionally align bar spacing for readability.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "abc2xmlArgs",
      type: "string",
      default: "",
      section: "Tools",
      group: "ABC <-> MusicXML",
      groupOrder: 10,
      label: "abc2xml flags",
      help: "Space-separated flags passed to abc2xml.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "xml2abcArgs",
      type: "string",
      default: "",
      section: "Tools",
      group: "ABC <-> MusicXML",
      groupOrder: 10,
      label: "xml2abc flags",
      help: "Space-separated flags passed to xml2abc.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "stripImportedMeasureComments",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "ABC <-> MusicXML",
      groupOrder: 10,
      label: "Remove imported measure comments",
      help: "Remove xml2abc comments such as %7 and %14 from imported ABC text.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "autoFormatImportedAbc",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "ABC <-> MusicXML",
      groupOrder: 10,
      label: "Auto-format imported ABC",
      help: "Apply the standard ABCarus line-break and bar alignment pass after import.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "midiImportBackend",
      type: "string",
      default: "auto",
      section: "Tools",
      group: "MIDI import",
      groupOrder: 20,
      label: "MIDI import backend",
      help: "Choose MIDI import engine. Auto prefers midi2xml (music21) with fallback to bundled midi2abc.",
      ui: {
        input: "select",
        options: [
          { value: "auto", label: "Auto (prefer midi2xml/music21)" },
          { value: "midi2abc", label: "Bundled midi2abc" },
          { value: "music21-xml2abc", label: "midi2xml (music21) -> xml2abc" },
        ],
      },
      advanced: true,
    },
    {
      key: "midi2abcArgs",
      type: "string",
      default: "",
      section: "Tools",
      group: "MIDI import",
      groupOrder: 20,
      label: "MIDI import flags",
      help: "Space-separated flags for MIDI import. Common: --title --composer --meter --unit --key. Bundled backend also supports --no-quantize --grid 1/8|1/16|1/32.",
      ui: { input: "text", placeholder: "--title \"My Tune\" --meter 4/4 --key Dm --grid 1/16" },
      advanced: true,
    },
    {
      key: "mp3ExportTimidityPath",
      type: "string",
      default: "",
      section: "Tools",
      group: "MP3 export",
      groupOrder: 30,
      label: "MP3 export: TiMidity++ path",
      help: "Optional absolute path to timidity. Leave empty to auto-detect in PATH.",
      ui: { input: "text", placeholder: "/usr/bin/timidity" },
      advanced: true,
    },
    {
      key: "mp3ExportFfmpegPath",
      type: "string",
      default: "",
      section: "Tools",
      group: "MP3 export",
      groupOrder: 30,
      label: "MP3 export: FFmpeg path",
      help: "Optional absolute path to ffmpeg. Leave empty to auto-detect in PATH.",
      ui: { input: "text", placeholder: "/usr/bin/ffmpeg" },
      advanced: true,
    },
    {
      key: "chordproBinPath",
      type: "string",
      default: "",
      section: "Tools",
      group: "ChordPro",
      groupOrder: 40,
      label: "ChordPro: binary path",
      help: "Optional absolute path to chordpro executable. Leave empty to auto-detect in PATH.",
      ui: { input: "text", placeholder: "/usr/bin/chordpro" },
      advanced: true,
    },
    {
      key: "chordproRepoPath",
      type: "string",
      default: "",
      section: "Tools",
      group: "ChordPro",
      groupOrder: 40,
      label: "ChordPro: repo path",
      help: "Optional path to a ChordPro source checkout (expects script/chordpro.pl).",
      ui: { input: "text", placeholder: "/path/to/chordpro" },
      advanced: true,
    },
    {
      key: "midiInputEnabled",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Enable MIDI input (step)",
      help: "Insert ABC notes at the cursor from a MIDI keyboard (step input).",
      ui: { input: "checkbox" },
    },
    {
      key: "midiInputMuted",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Mute MIDI input",
      help: "Ignore incoming MIDI notes without disabling the feature.",
      ui: { input: "checkbox" },
    },
    {
      key: "midiInputKeyAware",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Key-aware spelling",
      help: "Use the current K: signature to choose sharps/flats when entering notes.",
      ui: { input: "checkbox" },
    },
    {
      key: "midiInputGrid",
      type: "string",
      default: "1/16",
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Step grid (note length)",
      help: "Length applied to inserted notes relative to L: (1/8, 1/16, 1/32).",
      ui: {
        input: "select",
        options: [
          { value: "1/8", label: "1/8" },
          { value: "1/16", label: "1/16" },
          { value: "1/32", label: "1/32" },
        ],
      },
    },
    {
      key: "midiInputMacroEnabled",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Enable MIDI text macros",
      help: "Use low MIDI notes (24–35) for space/barline/backspace shortcuts.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "midiInputBeepEnabled",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Note preview on MIDI input",
      help: "Play a short WebAudio note preview for each incoming MIDI note.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "midiInputBeepVolume",
      type: "number",
      default: 0.2,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "MIDI preview volume (%)",
      help: "Volume for MIDI input note preview (0–100%).",
      ui: { input: "percent", min: 0, max: 100, step: 5 },
      advanced: true,
    },
    {
      key: "midiInputBeepDuration",
      type: "number",
      default: 140,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "MIDI preview duration (ms)",
      help: "Duration of MIDI input note preview (40–400ms).",
      ui: { input: "number", min: 40, max: 400, step: 10 },
      advanced: true,
    },
    {
      key: "noteTypingPreviewEnabled",
      type: "boolean",
      default: false,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Play notes while typing",
      help: "Preview a typed ABC note when it is completed with a delimiter (space, barline, tab, or newline).",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "noteTypingPreviewVolume",
      type: "number",
      default: 0.22,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview volume (%)",
      help: "Volume for typed-note preview (0–100%).",
      ui: { input: "percent", min: 0, max: 100, step: 5 },
      advanced: true,
    },
    {
      key: "noteTypingPreviewLengthMode",
      type: "string",
      default: "typed",
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview length mode",
      help: "Use typed duration suffixes, or always use base length L: for preview.",
      ui: {
        input: "select",
        options: [
          { value: "typed", label: "Use typed duration" },
          { value: "base", label: "Use base length (L:)" },
        ],
      },
      advanced: true,
    },
    {
      key: "noteTypingPreviewTrigger",
      type: "string",
      default: "delimiter",
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview trigger",
      help: "Choose when preview plays: after a delimiter, or immediately when typing a note letter.",
      ui: {
        input: "select",
        options: [
          { value: "delimiter", label: "On delimiter (space, bar, tab, newline)" },
          { value: "note", label: "Immediately on note letter" },
        ],
      },
      advanced: true,
    },
    {
      key: "noteTypingPreviewEnvelope",
      type: "string",
      default: "short",
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview envelope",
      help: "Short is tight for fast typing; Medium adds a longer tail.",
      ui: {
        input: "select",
        options: [
          { value: "short", label: "Short" },
          { value: "medium", label: "Medium" },
        ],
      },
      advanced: true,
    },
    {
      key: "noteTypingPreviewRetriggerDuration",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview: retrigger on duration",
      help: "In immediate trigger mode, replay the note when duration suffix is typed (for example C -> C4 or C/).",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "noteTypingPreviewSkipMicrotones",
      type: "boolean",
      default: true,
      section: "Tools",
      group: "MIDI Input",
      groupOrder: 30,
      label: "Typing preview: skip microtonal tokens",
      help: "When enabled, tokens that look microtonal/unsupported are ignored by typing preview.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "globalHeaderEnabled",
      type: "boolean",
      default: true,
      section: "Header",
      group: "Global header",
      groupOrder: 10,
      label: "Enable global header",
      help: "Prepended before file headers and tunes during render/playback.",
      ui: { input: "checkbox" },
    },
    {
      key: "globalHeaderText",
      type: "string",
      default: "",
      legacy: true,
      propertiesExport: false,
    },
    {
      key: "abc2svgNotationFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      group: "Notation",
      groupOrder: 10,
      label: "Notation font",
      help: "Optional SMuFL notation font override for abc2svg (%%musicfont).",
      ui: { input: "select", options: "notationFonts" },
    },
    {
      key: "abc2svgTextFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      group: "Notation",
      groupOrder: 10,
      label: "Text font",
      help: "Optional text font override for abc2svg titles/labels.",
      ui: { input: "select", options: "textFonts" },
    },
    {
      key: "uiFontFamily",
      type: "string",
      default: "system-ui, -apple-system, \"Segoe UI\", Roboto, Ubuntu, Cantarell, \"Noto Sans\", sans-serif",
      section: "Fonts",
      group: "Interface",
      groupOrder: 5,
      label: "Font family",
      help: "CSS font-family used for the app interface (does not affect the OS menu bar).",
      ui: { input: "select", options: "interfaceFonts" },
    },
    {
      key: "uiFontSize",
      type: "number",
      default: 13,
      section: "Fonts",
      group: "Interface",
      groupOrder: 5,
      label: "Font size",
      help: "Font size for the app interface (px).",
      ui: { input: "number", min: 10, max: 28, step: 1 },
    },
    {
      key: "libraryUiFontFamily",
      type: "string",
      default: "system-ui, -apple-system, \"Segoe UI\", Roboto, Ubuntu, Cantarell, \"Noto Sans\", sans-serif",
      section: "Fonts",
      group: "Interface",
      groupOrder: 5,
      label: "Library font family",
      help: "Optional override for the Library list.",
      ui: { input: "select", options: "interfaceFonts" },
    },
    {
      key: "libraryUiFontSize",
      type: "number",
      default: 12,
      section: "Fonts",
      group: "Interface",
      groupOrder: 5,
      label: "Library font size",
      help: "Optional override for the Library list font size (px).",
      ui: { input: "number", min: 10, max: 40, step: 1 },
    },
    {
      key: "printPageMargins",
      type: "string",
      default: "standard",
      section: "Print",
      group: "Page",
      groupOrder: 5,
      label: "Page margins",
      help: "Controls the outer page margins for single-tune, Print All, and Set List output. ABC margin directives still control the score inside the page.",
      ui: {
        input: "select",
        options: [
          { value: "standard", label: "Standard" },
          { value: "narrow", label: "Narrow" },
          { value: "none", label: "None" },
        ],
      },
    },
    {
      key: "printAllPageBreaks",
      type: "string",
      default: "perTune",
      section: "Print",
      group: "All tunes",
      groupOrder: 10,
      label: "Print All: page breaks",
      help: "Per tune prints each tune on a separate page. Continuous prints tunes back-to-back; use %%newpage in ABC to force page breaks.",
      ui: {
        input: "select",
        options: [
          { value: "perTune", label: "Per tune" },
          { value: "continuous", label: "Continuous (use %%newpage)" },
        ],
      },
    },
    {
      key: "printAllAskEachTime",
      type: "boolean",
      default: true,
      section: "Print",
      group: "All tunes",
      groupOrder: 10,
      label: "Ask before Print All",
      help: "When enabled, shows the Print All options dialog each time.",
      ui: { input: "checkbox" },
    },
    {
      key: "printSourceQrCodes",
      type: "boolean",
      default: false,
      section: "Print",
      group: "Source links",
      groupOrder: 20,
      label: "Print source QR codes",
      help: "When enabled, print/PDF output adds a small QR code next to readable F: source URLs.",
      ui: { input: "checkbox" },
    },
    {
      key: "editorFontFamily",
      type: "string",
      default: "\"ABCarus DejaVu Sans Mono\", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Font family",
      help: "Font used in the ABC editor.",
      ui: { input: "select", options: [] },
    },
    {
      key: "editorFontSize",
      type: "number",
      default: 13,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Font size",
      help: "Font size used in the ABC editor.",
      ui: { input: "number", min: 8, max: 32, step: 1 },
    },
    {
      key: "editorNotesBold",
      type: "boolean",
      default: true,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Bold notes",
      help: "Renders ABC note letters in bold in the editor.",
      ui: { input: "checkbox" },
    },
    {
      key: "editorLyricsBold",
      type: "boolean",
      default: true,
      section: "Fonts",
      group: "Editor",
      groupOrder: 40,
      label: "Bold inline lyrics",
      help: "Renders inline lyrics (w:) in bold in the editor.",
      ui: { input: "checkbox" },
    },
    {
      key: "usePortalFileDialogs",
      type: "boolean",
      default: platformDefaults.usePortalFileDialogs,
      section: "Dialogs",
      group: "File dialogs",
      groupOrder: 10,
      label: "Use portal file dialogs (Linux)",
      help: "Improves Open/Save dialog placement on some Linux desktops.",
      ui: { input: "checkbox" },
    },
    {
      key: "confirmAppendToActiveFile",
      type: "boolean",
      default: true,
      section: "Dialogs",
      group: "Confirmations",
      groupOrder: 20,
      label: "Confirm append to active file",
      help: "When enabled, shows a confirmation dialog before appending (e.g., after moving/copying a tune into the active file).",
      ui: { input: "checkbox" },
    },
    {
      key: "libraryAutoRenumberAfterMove",
      type: "boolean",
      default: false,
      section: "Library",
      group: "Behavior",
      groupOrder: 10,
      label: "Auto-renumber X after move",
      help: "When moving a tune between files, renumber X headers in both files to be sequential (starting at the first X).",
      ui: { input: "checkbox" },
    },
    {
      key: "libraryCacheEnabled",
      type: "boolean",
      default: false,
      section: "Library",
      group: "Performance",
      groupOrder: 15,
      label: "Enable library cache",
      help: "Keeps Library Catalog rows cached between opens. Disable for simpler, always-fresh behavior.",
      ui: { input: "checkbox" },
    },
    {
      key: "libraryResetCache",
      type: "action",
      default: null,
      section: "Library",
      group: "Performance",
      groupOrder: 15,
      label: "Reset library cache",
      help: "Clears cached Library Catalog rows and rebuilds from the current index.",
      ui: { input: "action" },
    },
    {
      key: "libraryTitleKeyLength",
      type: "number",
      default: 25,
      section: "Library",
      group: "Grouping",
      groupOrder: 15,
      label: "Title key length",
      help: "Maximum length for the normalized title key used by Group by: T (Title key).",
      ui: { input: "number", min: 1, max: 200, step: 1 },
    },
    {
      key: "libraryTitleKeyStrict",
      type: "boolean",
      default: false,
      section: "Library",
      group: "Grouping",
      groupOrder: 15,
      label: "Strict title key (no normalization)",
      help: "When enabled, Title key grouping uses the raw title (trimmed) without normalization.",
      ui: { input: "checkbox" },
    },
    {
      key: "templatesFolder",
      type: "string",
      default: "",
      section: "Library",
      group: "Templates",
      groupOrder: 20,
      label: "Templates folder",
      help: "Optional folder with .abc files used as tune templates. If empty, ABCarus uses the OS Templates folder when available, otherwise its default templates folder under user data.",
      ui: { input: "text" },
    },
    // Non-modal / internal / persisted UI prefs (kept for compatibility).
    { key: "soundfontPaths", type: "array", default: [], section: "Advanced", advanced: true, legacy: true },
    { key: "disclaimerSeen", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "errorsEnabled", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "usePortalFileDialogsSetByUser", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneVisible", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneWidth", type: "number", default: 280, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryGroupBy", type: "string", default: "file", section: "Advanced", advanced: true, legacy: true },
    { key: "librarySortBy", type: "string", default: "update_desc", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryTuneSortBy", type: "string", default: "x_asc", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryFilterText", type: "string", default: "", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryUiStateByRoot", type: "object", default: {}, section: "Advanced", advanced: true, legacy: true },
  ];
}

function getDefaultSettingsFromSchema(schema) {
  const out = {};
  for (const entry of schema) {
    if (!entry || !entry.key) continue;
    out[entry.key] = entry.default;
  }
  return out;
}

function getDefaultSettings() {
  return getDefaultSettingsFromSchema(getSettingsSchema());
}

module.exports = {
  getSettingsSchema,
  getDefaultSettings,
};
