function getPlatformDefaults() {
  return {
    // On Cinnamon/GTK, native file dialogs can appear off-screen; portal dialogs are more reliable.
    usePortalFileDialogs: process.platform === "linux",
  };
}

function getSettingsSchema() {
  const platformDefaults = getPlatformDefaults();
  return [
    {
      key: "renderZoom",
      type: "number",
      default: 1,
      section: "General",
      label: "Score zoom (%)",
      help: "Zoom level for the rendered score (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "editorZoom",
      type: "number",
      default: 1,
      section: "General",
      label: "Editor zoom (%)",
      help: "Zoom level for the editor (50–800%).",
      ui: { input: "percent", min: 50, max: 800, step: 5 },
    },
    {
      key: "followPlayback",
      type: "boolean",
      default: true,
      section: "Playback",
      label: "Follow playback",
      help: "Controls the Follow toggle in the toolbar.",
      // UI control lives in the main toolbar, not in the Settings modal.
    },
    {
      key: "followHighlightColor",
      type: "string",
      default: "#1e90ff",
      section: "Playback",
      label: "Follow highlight color",
      help: "Used for the Follow bar highlight and the playback playhead line in the score.",
      ui: { input: "color" },
    },
    {
      key: "followHighlightBarOpacity",
      type: "number",
      default: 0.12,
      section: "Playback",
      label: "Follow bar opacity (%)",
      help: "Opacity for the current bar highlight in the score (0–60%).",
      ui: { input: "percent", min: 0, max: 60, step: 1 },
    },
    {
      key: "followMeasureOpacity",
      type: "number",
      default: 0.08,
      section: "Playback",
      label: "Follow staff opacity (%)",
      help: "Opacity for the current staff highlight during playback (0–30%).",
      ui: { input: "percent", min: 0, max: 30, step: 1 },
    },
    {
      key: "followPlayheadOpacity",
      type: "number",
      default: 0.7,
      section: "Playback",
      label: "Follow playhead opacity (%)",
      help: "Opacity for the vertical playhead line in the score (0–100%).",
      ui: { input: "percent", min: 0, max: 100, step: 1 },
    },
    {
      key: "followPlayheadWidth",
      type: "number",
      default: 2,
      section: "Playback",
      label: "Follow playhead width (px)",
      help: "Thickness of the vertical playhead line in the score (1–6px).",
      ui: { input: "number", min: 1, max: 6, step: 1 },
    },
    {
      key: "followPlayheadPad",
      type: "number",
      default: 8,
      section: "Playback",
      label: "Playhead extra height (px)",
      help: "Extends the playhead line slightly above/below the staff (0–24px).",
      ui: { input: "number", min: 0, max: 24, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadBetweenNotesWeight",
      type: "number",
      default: 1,
      section: "Playback",
      label: "Playhead between notes (%)",
      help: "100% = between previous and current note; 0% = on the current note.",
      ui: { input: "percent", min: 0, max: 100, step: 5 },
      advanced: true,
    },
    {
      key: "followPlayheadShift",
      type: "number",
      default: 0,
      section: "Playback",
      label: "Playhead horizontal shift (px)",
      help: "Negative values move the playhead left; positive move it right (-20…20).",
      ui: { input: "number", min: -20, max: 20, step: 1 },
      advanced: true,
    },
    {
      key: "followPlayheadFirstBias",
      type: "number",
      default: 6,
      section: "Playback",
      label: "First-note bias (px)",
      help: "When there is no previous note to interpolate from, bias the playhead slightly left (0–20).",
      ui: { input: "number", min: 0, max: 20, step: 1 },
      advanced: true,
    },
	    {
	      key: "playbackAutoScrollMode",
	      type: "string",
	      default: "Keep Visible",
	      section: "Playback",
	      label: "Playback auto-scroll",
	      help: "Keeps the playhead visible while playing, scrolling the score automatically.",
	      ui: {
	        input: "select",
	        options: [
	          { value: "Off", label: "Off" },
	          { value: "Keep Visible", label: "Keep Cursor Visible" },
	          { value: "Page Turn", label: "Smooth Follow" },
	          { value: "Centered", label: "Center Cursor" },
	        ],
	      },
	    },
    {
      key: "playbackAutoScrollHorizontal",
      type: "boolean",
      default: true,
      section: "Playback",
      label: "Allow horizontal auto-scroll",
      help: "When needed (high zoom), also scroll horizontally to keep the playhead visible.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "playbackAutoScrollPauseMs",
      type: "number",
      default: 1800,
      section: "Playback",
      label: "Auto-scroll pause after manual scroll (ms)",
      help: "Temporarily pauses auto-scroll after the user scrolls manually (0–5000ms).",
      ui: { input: "number", min: 0, max: 5000, step: 100 },
      advanced: true,
    },
    {
      key: "soundfontName",
      type: "string",
      default: "TimGM6mb.sf2",
      section: "Fonts",
      label: "Soundfont (SF2)",
      help: "Default soundfont for playback. You can add/remove user soundfonts here.",
      ui: { input: "select", options: "soundfonts" },
    },
    {
      key: "drumVelocityMap",
      type: "object",
      default: {},
      section: "Drums",
      label: "Drum mixer",
      help: "Default velocities for GM drum pitches. Tune-specific velocities still apply.",
      ui: { input: "drumVelocityMap" },
      advanced: true,
    },
    {
      key: "useNativeTranspose",
      type: "boolean",
      default: true,
      section: "Tools",
      label: "Use native transpose",
      help: "When enabled, semitone transposition runs via the built-in JS engine.",
      ui: { input: "checkbox" },
    },
    {
      key: "autoAlignBarsAfterTransforms",
      type: "boolean",
      default: false,
      section: "Tools",
      label: "Auto-align bars after transforms",
      help: "After running a transform, optionally align bar spacing for readability.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "abc2xmlArgs",
      type: "string",
      default: "",
      section: "Import/Export",
      label: "abc2xml flags",
      help: "Space-separated flags passed to abc2xml.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "xml2abcArgs",
      type: "string",
      default: "",
      section: "Import/Export",
      label: "xml2abc flags",
      help: "Space-separated flags passed to xml2abc.",
      ui: { input: "text", placeholder: "-x -y=value" },
      advanced: true,
    },
    {
      key: "globalHeaderEnabled",
      type: "boolean",
      default: true,
      section: "Header",
      label: "Enable global header",
      help: "Prepended before file headers and tunes during render/playback.",
      ui: { input: "checkbox" },
    },
    {
      key: "globalHeaderText",
      type: "string",
      default: "",
      section: "Header",
      label: "Global header",
      help: "Prepended before file headers and tunes during render/playback.",
      ui: { input: "code" },
    },
    {
      key: "abc2svgNotationFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      label: "Notation font",
      help: "Optional SMuFL notation font override for abc2svg (uses %%musicfont). Leave empty to use the default.",
      ui: { input: "select", options: "notationFonts" },
    },
    {
      key: "abc2svgTextFontFile",
      type: "string",
      default: "",
      section: "Fonts",
      label: "Text font",
      help: "Optional text font override for abc2svg titles/labels (uses %%...font directives). Leave empty to use the default.",
      ui: { input: "select", options: "textFonts" },
    },
    {
      key: "editorFontFamily",
      type: "string",
      default: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
      section: "Editor",
      label: "Font family",
      ui: { input: "text" },
    },
    {
      key: "editorFontSize",
      type: "number",
      default: 13,
      section: "Editor",
      label: "Font size",
      ui: { input: "number", min: 8, max: 32, step: 1 },
    },
    {
      key: "editorNotesBold",
      type: "boolean",
      default: true,
      section: "Editor",
      label: "Bold notes",
      ui: { input: "checkbox" },
    },
    {
      key: "editorLyricsBold",
      type: "boolean",
      default: true,
      section: "Editor",
      label: "Bold inline lyrics",
      ui: { input: "checkbox" },
    },
    {
      key: "usePortalFileDialogs",
      type: "boolean",
      default: platformDefaults.usePortalFileDialogs,
      section: "Dialogs",
      label: "Use portal file dialogs (Linux)",
      help: "Improves Open/Save dialog placement on some Linux desktops.",
      ui: { input: "checkbox" },
      advanced: true,
    },
    {
      key: "libraryAutoRenumberAfterMove",
      type: "boolean",
      default: false,
      section: "Library",
      label: "Auto-renumber X after move",
      help: "When moving a tune between files, renumber X headers in both files to be sequential (starting at the first X).",
      ui: { input: "checkbox" },
    },
    // Non-modal / internal / persisted UI prefs (kept for compatibility).
    { key: "soundfontPaths", type: "array", default: [], section: "Advanced", advanced: true, legacy: true },
    { key: "disclaimerSeen", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "errorsEnabled", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "usePortalFileDialogsSetByUser", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneVisible", type: "boolean", default: false, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryPaneWidth", type: "number", default: 280, section: "Advanced", advanced: true, legacy: true },
    { key: "libraryGroupBy", type: "string", default: "file", section: "Advanced", advanced: true, legacy: true },
    { key: "librarySortBy", type: "string", default: "update_desc", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryFilterText", type: "string", default: "", section: "Advanced", advanced: true, legacy: true },
    { key: "libraryUiStateByRoot", type: "object", default: {}, section: "Advanced", advanced: true, legacy: true },
  ];
}

function getDefaultSettingsFromSchema(schema) {
  const out = {};
  for (const entry of schema) {
    if (!entry || !entry.key) continue;
    out[entry.key] = entry.default;
  }
  return out;
}

function getDefaultSettings() {
  return getDefaultSettingsFromSchema(getSettingsSchema());
}

module.exports = {
  getSettingsSchema,
  getDefaultSettings,
};
