import { createPlaybackUiController } from "../app/ui/playback_ui_controller.js";
import { createAbSelectionPlaybackController } from "./ab_selection_playback_controller.js";
import { createDrumPreviewController } from "./drum_preview_controller.js";
import { createFocusModeController } from "./focus_mode_controller.js";
import { createPlaybackAutoScrollController } from "./playback_autoscroll_controller.js";
import { createPlaybackFollowController } from "./playback_follow_controller.js";
import { createPlaybackPayloadController } from "./playback_payload_controller.js";
import { createPlaybackPlayerController } from "./playback_player_controller.js";
import { createPlaybackPrepareController } from "./playback_prepare_controller.js";
import { createPlaybackStartController } from "./playback_start_controller.js";
import { createPlaybackTransportController } from "./playback_transport_controller.js";
import {
  buildSelectionPlaybackToast,
  hasIntentionalSelectionPlaybackSpan,
  hasRepeatTokensInSlice,
  parseMutedVoiceSetting,
} from "./selection_playback_model.js";
import { createSoundfontController } from "./soundfont_controller.js";

export function createPlaybackComposition({
  domain,
  transport,
  selectionRuntime,
  abLoopRuntime,
  windowRef,
  documentRef,
  api,
  elements,
  host,
}) {
  let uiController = null;

  const soundfontController = createSoundfontController({
    windowRef,
    api,
    elements: { label: elements.soundfontLabel },
    state: {
      isPlaying: domain.isPlaying,
      isPaused: domain.isPaused,
      isWaitingForFirstNote: domain.isWaitingForFirstNote,
    },
    actions: {
      ensurePlayer: domain.ensurePlayer,
      setBufferStatus: host.setBufferStatus,
      setStatus: host.setStatus,
      showToast: host.showToast,
      stopPlayback: domain.stopFromGuard,
    },
  });
  soundfontController.installRuntimeErrorHandler();

  const abSelectionController = createAbSelectionPlaybackController({
    abLoopRuntime,
    selectionPlaybackRuntime: selectionRuntime,
    getSettings: () => ({
      ...(host.getSettings() || {}),
      selectionLoopElement: elements.selectionLoopEnabled,
      selectionSuppressElement: elements.selectionSuppressEnabled,
      selectionGchordsElement: elements.selectionGchordsEnabled,
      selectionDrumsElement: elements.selectionDrumsEnabled,
      selectionMutedVoicesElement: elements.selectionMutedVoices,
    }),
    getEditorView: host.getEditorView,
    getEditorText: host.getEditorText,
    isRawMode: host.isRawMode,
    isPayloadMode: host.isPayloadMode,
    isPlaying: domain.isPlaying,
    getPlaybackRange: domain.getRange,
    getActivePlaybackRange: domain.getActiveRange,
    setPlaybackRange: domain.setRange,
    startPlaybackFromRange: domain.startFromRange,
    stopPlayback: domain.stopTransport,
    refreshMarkers: host.refreshEditor,
    showToast: host.showToast,
    parseMutedVoiceSetting,
    hasIntentionalSelectionPlaybackSpan,
    hasRepeatTokensInSlice,
    buildSelectionPlaybackToast,
    globalObject: windowRef,
  });

  const payloadController = createPlaybackPayloadController({
    transport,
    selectionRuntime,
    getEditorText: host.getEditorText,
    getActiveEntryHeader: host.getActiveEntryHeader,
    buildHeaderPrefix: host.buildHeaderPrefix,
    countLinesForPrefix: host.countLinesForPrefix,
    isChordProEnabled: host.isChordProEnabled,
    isChordProFullView: host.isChordProFullView,
    chordProHasBlocks: host.chordProHasBlocks,
    isPayloadMode: host.isPayloadMode,
    isPlaybackPayloadView: host.isPlaybackPayloadView,
    getExpandRepeats: host.getExpandRepeats,
    detectMeterMismatchInBarlines: host.detectMeterMismatchInBarlines,
    detectRepeatMarkerAfterShortBar: host.detectRepeatMarkerAfterShortBar,
    neutralizeMidiDrumDirectivesForPlayback: host.neutralizeMidiDrumDirectivesForPlayback,
    assertCleanAbcText: host.assertCleanAbcText,
    showToast: host.showToast,
  });

  const prepareController = createPlaybackPrepareController({
    windowRef,
    transport,
    selectionRuntime,
    ensureSoundfontReady: soundfontController.ensureReady,
    ensurePlayer: domain.ensurePlayer,
    getAbcCtor: host.getAbcCtor,
    getPlaybackPayload: domain.getPayload,
    getPlaybackSourceKey: domain.getSourceKey,
    buildPlaybackState: domain.buildState,
    setFollowVoiceFromPlayback: domain.setFollowVoiceFromPlayback,
    clearErrors: host.clearErrors,
    setStatus: host.setStatus,
    showToast: host.showToast,
    logErr: host.logErr,
    addError: host.addError,
    setErrorLineOffsetFromHeader: host.setErrorLineOffsetFromHeader,
    setErrorsLineOffset: host.setErrorsLineOffset,
    parseErrorLocation: host.parseErrorLocation,
    scheduleAutoDump: host.scheduleAutoDump,
    assertCleanAbcText: host.assertCleanAbcText,
    neutralizeMidiDrumDirectivesForPlayback: host.neutralizeMidiDrumDirectivesForPlayback,
    isMidiDrumMustBeInVoicePlaybackError: host.isMidiDrumMustBeInVoicePlaybackError,
    hasMidiDrumMustBeInVoicePlaybackError: host.hasMidiDrumMustBeInVoicePlaybackError,
    shouldRelocateMidiDrumsForPlayback: host.shouldRelocateMidiDrumsForPlayback,
    normalizeAccThreeQuarterToneForAbc2svg: host.normalizeAccThreeQuarterToneForAbc2svg,
    isChordProFullView: host.isChordProFullView,
  });

  const startController = createPlaybackStartController({
    transport,
    selectionRuntime,
    getEditorView: host.getEditorView,
    getPlaybackRange: domain.getRange,
    setPlaybackRange: domain.setRange,
    clonePlaybackRange: domain.cloneRange,
    getPlaybackSourceKey: domain.getSourceKey,
    preparePlayback: domain.prepare,
    ensureSoundfontReady: soundfontController.ensureReady,
    stopPlaybackForRestart: domain.stopForRestart,
    stopPlaybackFromGuard: domain.stopFromGuard,
    recordDebugLog: host.recordDebugLog,
    scheduleAutoDump: host.scheduleAutoDump,
    setStatus: host.setStatus,
    updatePlayButton: domain.updatePlayButton,
    clearNoteSelection: host.clearNoteSelection,
    resetPlaybackUiState: domain.resetUiState,
    setSoundfontCaption: soundfontController.setCaption,
    showToast: host.showToast,
    updatePracticeUi: domain.updatePracticeUi,
    getScopedPlaybackSettingsForOrigin: domain.getScopedSettingsForOrigin,
    withScopedPlaybackOrigin: domain.withScopedOrigin,
    getStripChordSymbols: host.getStripChordSymbols,
    toDerivedOffset: domain.toDerivedOffset,
    toEditorOffset: domain.toEditorOffset,
    findSymbolAtOrAfter: domain.findSymbolAtOrAfter,
    findSymbolAtOrBefore: domain.findSymbolAtOrBefore,
    findMeasureIndex: domain.findMeasureIndex,
    isFollowPlaybackEnabled: domain.isFollowEnabled,
    getDebugParts: host.getDebugParts,
  });

  const transportController = createPlaybackTransportController({
    transport,
    selectionRuntime,
    getEditorView: host.getEditorView,
    getEditorText: host.getEditorText,
    findMeasureStartOffsetByNumber: host.findMeasureStartOffsetByNumber,
    getFocusModeEnabled: domain.isFocusEnabled,
    normalizeFocusLoopBoundsForPlayback: domain.normalizeFocusLoopBoundsForPlayback,
    computeFocusPlaybackPlanFromCurrentState: domain.computeFocusPlan,
    startPlaybackFromRange: domain.startFromRange,
    startPlaybackAtIndex: domain.startAtIndex,
    pausePlayback: domain.pause,
    playSelectionOnce: domain.playSelectionOnce,
    setPracticeBarHighlight: host.setPracticeBarHighlight,
    clearSvgPracticeBarHighlight: host.clearSvgPracticeBarHighlight,
    playbackGuardError: (message) => {
      if (uiController) uiController.reportPlaybackGuardError(message);
    },
    stopPlaybackFromGuard: domain.stopFromGuard,
    setStatus: host.setStatus,
    updatePlayButton: domain.updatePlayButton,
    clearNoteSelection: host.clearNoteSelection,
    resetPlaybackUiState: domain.resetUiState,
    setSoundfontCaption: soundfontController.setCaption,
    showToast: host.showToast,
  });

  const autoScrollController = createPlaybackAutoScrollController({
    windowRef,
    consoleRef: host.consoleRef,
    getRenderPane: () => elements.renderPane,
    getOutElement: () => elements.output,
    getPlayheadElement: host.getPlayheadElement,
    isPlaybackBusy: domain.isBusy,
    clampNumber: host.clampNumber,
    getRenderZoomFactor: host.getRenderZoomFactor,
    isDebugEnabled: host.isAutoScrollDebugEnabled,
  });

  const followController = createPlaybackFollowController({
    windowRef,
    transport,
    getEditorView: host.getEditorView,
    getOutElement: () => elements.output,
    getRenderPane: () => elements.renderPane,
    getFollowPlaybackEnabled: domain.isFollowEnabled,
    getFocusModeEnabled: domain.isFocusEnabled,
    clearSvgPlayhead: host.clearSvgPlayhead,
    clearSvgFollowBarHighlight: host.clearSvgFollowBarHighlight,
    clearSvgFollowMeasureHighlight: host.clearSvgFollowMeasureHighlight,
    clearSvgPracticeBarHighlight: host.clearSvgPracticeBarHighlight,
    setPracticeBarHighlight: host.setPracticeBarHighlight,
    findSymbolAtOrBefore: domain.findSymbolAtOrBefore,
    upperBoundTime: domain.upperBoundTime,
    snapIstartToPlayable: domain.snapIstartToPlayable,
    mapEditorOffsetToRenderIdx: host.mapEditorOffsetToRenderIdx,
    mapRenderIdxToEditorOffset: host.mapRenderIdxToEditorOffset,
    findNearestNoteHighlightElements: host.findNearestNoteHighlightElements,
    pickClosestNoteElement: host.pickClosestNoteElement,
    extractRenderIdxFromElementClass: host.extractRenderIdxFromElementClass,
    findNearestBarElForNote: host.findNearestBarElForNote,
    setSvgPlayheadFromElements: host.setSvgPlayheadFromElements,
    highlightSvgFollowMeasureForNote: host.highlightSvgFollowMeasureForNote,
    maybeAutoScrollRenderToCursor: domain.maybeAutoScrollRenderToCursor,
    cancelPlaybackAutoScroll: domain.cancelAutoScroll,
  });

  const playerController = createPlaybackPlayerController({
    windowRef,
    transport,
    selectionRuntime,
    getEditorView: host.getEditorView,
    getFocusModeEnabled: domain.isFocusEnabled,
    getFollowPlaybackEnabled: domain.isFollowEnabled,
    getSoundfontSource: soundfontController.getSource,
    setSuppressPlaybackRangeSelectionSync: host.setSuppressPlaybackRangeSelectionSync,
    applyPlaybackPlanSpeed: domain.applyPlanSpeed,
    startPlaybackFromRange: domain.startFromRange,
    updatePracticeUi: domain.updatePracticeUi,
    setStatus: host.setStatus,
    updatePlayButton: domain.updatePlayButton,
    clearNoteSelection: host.clearNoteSelection,
    clearPlaybackNoteOnEls: domain.clearNoteOnElements,
    clearSvgPlayhead: host.clearSvgPlayhead,
    clearSvgFollowBarHighlight: host.clearSvgFollowBarHighlight,
    clearSvgFollowMeasureHighlight: host.clearSvgFollowMeasureHighlight,
    resetPlaybackUiState: domain.resetUiState,
    setSoundfontCaption: soundfontController.setCaption,
    findSymbolAtOrBefore: domain.findSymbolAtOrBefore,
    toEditorOffset: domain.toEditorOffset,
    appendPlaybackTrace: domain.appendTrace,
    stopPlaybackFromGuard: domain.stopFromGuard,
    schedulePlaybackUiUpdate: domain.scheduleUiUpdate,
    logErr: host.logErr,
  });

  const drumPreviewController = createDrumPreviewController({
    transport,
    velocityToDynamic: host.velocityToDynamic,
    ensureSoundfontLoaded: soundfontController.ensureLoaded,
    ensurePlayer: domain.ensurePlayer,
    getAbcCtor: host.getAbcCtor,
    getSoundfontSource: soundfontController.getSource,
    stopPlaybackForRestart: domain.stopForRestart,
    updatePlayButton: domain.updatePlayButton,
    logErr: host.logErr,
    windowRef,
  });

  const focusController = createFocusModeController({
    elements: elements.focus,
    transport,
    getSettings: host.getSettings,
    getActiveTuneId: host.getActiveTuneId,
    getLibraryVisible: host.getLibraryVisible,
    isRawModeActive: host.isRawMode,
    isPlaybackBusy: domain.isBusy,
    isFocusBoundedPlaybackScope: domain.isFocusBoundedScope,
    getEditorView: host.getEditorView,
    getEditorText: host.getEditorText,
    getRenderMeasureIndex: host.getRenderMeasureIndex,
    getRenderCompatMap: host.getRenderCompatMap,
    mapRenderIdxToEditorOffset: host.mapRenderIdxToEditorOffset,
    getOutputElement: () => elements.output,
    getRenderPane: () => elements.renderPane,
    getScopedPlaybackSettingsForOrigin: domain.getScopedSettingsForOrigin,
    findMeasureStartOffsetByNumber: host.findPrimaryVoiceMeasureStart,
    clampInt: host.clampInt,
    readRenderZoom: host.readRenderZoom,
    setRenderZoom: host.setRenderZoom,
    computeFocusFitZoom: host.computeFocusFitZoom,
    setLibraryVisible: host.setLibraryVisible,
    resetRightPaneSplit: host.resetRightPaneSplit,
    syncPendingPlaybackPlan: domain.syncPendingPlan,
    clearNormalPlaybackPlan: host.clearNormalPlaybackPlan,
    stopPlaybackForRangeEdit: domain.stopTransport,
    persistLoopSettingsPatch: host.persistLoopSettingsPatch,
    showToast: host.showToast,
  });

  uiController = createPlaybackUiController({
    elements: elements.ui,
    state: {
      transport,
      selectionRuntime,
      getEditorView: host.getEditorView,
      getIsPlaying: domain.isPlaying,
      getIsPaused: domain.isPaused,
      getWaitingForFirstNote: domain.isWaitingForFirstNote,
      getFollowPlayback: domain.isFollowEnabled,
      isChordProEnabled: host.isChordProEnabled,
      isChordProFullView: host.isChordProFullView,
    },
    actions: {
      recordDebugLog: host.recordDebugLog,
      scheduleAutoDump: host.scheduleAutoDump,
      logPlaybackGuardError: host.logPlaybackGuardError,
      setStatus: host.setStatus,
      clearNoteSelection: host.clearNoteSelection,
      resetPlaybackUiState: domain.resetUiState,
      clearSvgPlayhead: host.clearSvgPlayhead,
      clearSvgFollowBarHighlight: host.clearSvgFollowBarHighlight,
      clearSvgFollowMeasureHighlight: host.clearSvgFollowMeasureHighlight,
      setButtonText: host.setButtonText,
      updateAbUi: domain.updateAbUi,
      updatePracticeUi: domain.updatePracticeUi,
    },
  });

  return {
    abSelection: abSelectionController,
    autoScroll: autoScrollController,
    drumPreview: drumPreviewController,
    focus: focusController,
    follow: followController,
    payload: payloadController,
    player: playerController,
    prepare: prepareController,
    soundfont: soundfontController,
    start: startController,
    transport: transportController,
    ui: uiController,
  };
}
