import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

function usage(exitCode = 1) {
  const msg = [
    "Usage:",
    "  node scripts/chat-log.mjs [DEVLOG.md] -m \"message\" [--notes \"optional notes\"]",
    "  node scripts/chat-log.mjs --file DEVLOG.md -m \"message\" [--notes \"optional notes\"]",
    "",
    "Notes:",
    "  - If -m/--message is omitted and stdin is a TTY, the script will prompt.",
    "",
    "Appends a new entry to DEVLOG.md with the current git state (branch/HEAD/status/diffstat).",
  ].join("\n");
  process.stderr.write(`${msg}\n`);
  process.exit(exitCode);
}

function parseArgs(argv) {
  const out = { message: "", notes: "", file: "" };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "-m" || a === "--message") out.message = String(argv[i + 1] || ""), i += 1;
    else if (a === "--notes") out.notes = String(argv[i + 1] || ""), i += 1;
    else if (a === "--file") out.file = String(argv[i + 1] || ""), i += 1;
    else if (a === "-h" || a === "--help") usage(0);
    else if (a.startsWith("-")) usage(1);
    else if (!out.file) out.file = String(a || "");
    else usage(1);
  }
  out.message = out.message.trim();
  out.notes = out.notes.trim();
  out.file = (out.file || "DEVLOG.md").trim();
  if (!out.file) out.file = "DEVLOG.md";
  if (!out.message) {
    if (process.stdin.isTTY) {
      process.stderr.write("Message: ");
      const buf = fs.readFileSync(0, "utf8");
      out.message = String(buf || "").trim();
    }
  }
  if (!out.message) usage(1);
  return out;
}

function run(cmd) {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }).trim();
  } catch (e) {
    const stderr = e && e.stderr ? String(e.stderr) : "";
    const stdout = e && e.stdout ? String(e.stdout) : "";
    return `${stdout}\n${stderr}`.trim();
  }
}

function nowStamp() {
  const d = new Date();
  const pad2 = (n) => String(n).padStart(2, "0");
  const y = d.getFullYear();
  const m = pad2(d.getMonth() + 1);
  const day = pad2(d.getDate());
  const hh = pad2(d.getHours());
  const mm = pad2(d.getMinutes());
  const ss = pad2(d.getSeconds());
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || "";
  return `${y}-${m}-${day} ${hh}:${mm}:${ss}${tz ? ` (${tz})` : ""}`;
}

function formatBlock(label, text) {
  const body = String(text || "").trim();
  if (!body) return "";
  return `\n**${label}**\n\n\`\`\`text\n${body}\n\`\`\`\n`;
}

const args = parseArgs(process.argv.slice(2));

const branch = run("git rev-parse --abbrev-ref HEAD");
const head = run("git rev-parse --short HEAD");
const subject = run("git log -1 --pretty=%s");
const status = run("git status --porcelain=v1");
const diffStat = run("git diff --stat");

const entry = [
  `## ${nowStamp()} — ${args.message}`,
  "",
  `- Branch: \`${branch}\``,
  `- HEAD: \`${head}\` (${subject})`,
  "",
  formatBlock("Git status (porcelain)", status || "(clean)"),
  formatBlock("Working tree diffstat", diffStat || "(no diff)"),
  args.notes ? `**Notes**\n\n${args.notes}\n` : "",
  "",
].join("\n");

const devlogPath = path.isAbsolute(args.file)
  ? args.file
  : path.join(process.cwd(), args.file);
if (!fs.existsSync(devlogPath)) {
  fs.writeFileSync(
    devlogPath,
    "# Development log (chat-driven)\n\n(Generated by `scripts/chat-log.mjs`.)\n\n",
    "utf8"
  );
}
fs.appendFileSync(devlogPath, entry, "utf8");
process.stdout.write(`Appended entry to ${devlogPath}\n`);
