// Shorthand decorations supported by the bundled abc2svg parser.
// Source: `third_party/abc2svg/core/parse.js` (`char_tb` mapping).
//
// This is intended as seed data for editor helpers (pickers, tooltips, etc.).
// Keep it simple and extend locally as needed (don’t import from `third_party/` at runtime).
export const ABC2SVG_CHAR_DECORATION_SHORTHANDS = [
  { char: ".", abc: "!dot!", name: "dot" },
  { char: "H", abc: "!fermata!", name: "fermata" },
  { char: "L", abc: "!emphasis!", name: "emphasis" },
  { char: "M", abc: "!lowermordent!", name: "lowermordent" },
  { char: "O", abc: "!coda!", name: "coda" },
  { char: "P", abc: "!uppermordent!", name: "uppermordent" },
  { char: "S", abc: "!segno!", name: "segno" },
  { char: "T", abc: "!trill!", name: "trill" },
  { char: "u", abc: "!upbow!", name: "upbow" },
  { char: "v", abc: "!downbow!", name: "downbow" },
  { char: "~", abc: "!gmark!", name: "gmark" },
];

export const ABC2SVG_CHAR_DECORATION_BY_CHAR = Object.fromEntries(
  ABC2SVG_CHAR_DECORATION_SHORTHANDS.map((x) => [x.char, x])
);

// Decorations defined by abc2svg (including its `// internal` section).
// Standard list generated by `node devtools/extract_abc2svg_decorations.mjs`.
// Internal list extracted from `third_party/abc2svg/core/deco.js` (`// internal` keys).
export const ABC2SVG_DECORATION_NAMES_STANDARD = [
  "-(",
  "-)",
  "^",
  "+",
  "<(",
  "<)",
  ">",
  ">(",
  ">)",
  "~(",
  "~)",
  "15ma(",
  "15ma)",
  "15mb(",
  "15mb)",
  "8va(",
  "8va)",
  "8vb(",
  "8vb)",
  "accent",
  "arpeggio",
  "breath",
  "caesura",
  "coda",
  "crescendo(",
  "crescendo)",
  "D.C.",
  "D.C.alcoda",
  "D.C.alfine",
  "D.S.",
  "D.S.alcoda",
  "D.S.alfine",
  "dacapo",
  "dacoda",
  "diminuendo(",
  "diminuendo)",
  "dot",
  "downbow",
  "emphasis",
  "f",
  "fermata",
  "ff",
  "fff",
  "ffff",
  "fine",
  "gmark",
  "invertedfermata",
  "invertedturn",
  "longphrase",
  "lowermordent",
  "marcato",
  "mediumphrase",
  "mf",
  "mordent",
  "mp",
  "open",
  "p",
  "ped",
  "ped-up",
  "ped(",
  "ped)",
  "plus",
  "pp",
  "ppp",
  "pppp",
  "pralltriller",
  "roll",
  "segno",
  "sfz",
  "short",
  "shortphrase",
  "slide",
  "snap",
  "tenuto",
  "thumb",
  "tick",
  "trill",
  "trill(",
  "trill)",
  "turn",
  "turnx",
  "upbow",
  "uppermordent",
  "wedge",
];

export const ABC2SVG_DECORATION_NAMES_INTERNAL = [
  "/",
  "//",
  "///",
  "beamon",
  "beam-accel",
  "beam-rall",
  "beambr1",
  "beambr2",
  "courtesy",
  "editorial",
  "fg",
  "invisible",
  "rbend",
  "rbstop",
  "sacc-1",
  "sacc1",
  "sacc3",
  "cacc-1",
  "cacc1",
  "cacc3",
  "stemless",
  "tie(",
  "tie)",
  "trem1",
  "trem2",
  "trem3",
  "trem4",
  "xstem",
];

const SHORT_BY_NAME = Object.fromEntries(
  ABC2SVG_CHAR_DECORATION_SHORTHANDS.map((x) => [x.name, x])
);

export const ABC2SVG_DECORATION_NAMES = Array.from(
  new Set([...ABC2SVG_DECORATION_NAMES_STANDARD, ...ABC2SVG_DECORATION_NAMES_INTERNAL])
).sort((a, b) => a.localeCompare(b));

const INTERNAL_SET = new Set(ABC2SVG_DECORATION_NAMES_INTERNAL);

export const ABC2SVG_DECORATIONS = ABC2SVG_DECORATION_NAMES.map((name) => ({
  name,
  abc: `!${name}!`,
  char: (SHORT_BY_NAME[name] && SHORT_BY_NAME[name].char) ? SHORT_BY_NAME[name].char : "",
  isInternal: INTERNAL_SET.has(name),
}));
