// Canonical Perde naming by ABC token (EDO-53 only).
//
// Source of truth (research workspace):
// - /home/avetik/Projects/Makams/tones_map_sorted.csv
//   Columns: Tone_name, ABC_Main, ABC_Enh
//
// Notes:
// - A single token can legitimately map to multiple names (synonyms), e.g. `_E`:
//   AşiranınYegâh / Şorizen.
// - Some entries in the source table may be ambiguous or imperfect; this map stays
//   literal and does not “correct” data.

export const PERDE_NAMES_BY_ABC_TOKEN = Object.freeze({
  "G,,": Object.freeze(["Kaba Rast"]),
  "A,": Object.freeze(["Kaba Dügâh"]),
  "_5B,": Object.freeze(["Kaba Dik Segâh"]),
  "^4A,": Object.freeze(["Kaba Dik Segâh"]),
  "_1B,": Object.freeze(["Kaba Segâh"]),
  "^8A,": Object.freeze(["Kaba Segâh"]),
  "B,": Object.freeze(["Kaba Bûselik"]),
  "^4C": Object.freeze(["Kaba Nim Hicâz", "Pes.Hicâz"]),
  "_5D": Object.freeze(["Kaba Nim Hicâz", "Pes.Hicâz"]),
  "C": Object.freeze(["Kaba Çârgâh"]),
  "_1D": Object.freeze(["Kaba Dik Hicâz"]),
  "^8C": Object.freeze(["Kaba Dik Hicâz"]),
  "D": Object.freeze(["Yegâh"]),
  "^4D": Object.freeze(["Kaba Nim Hisâr"]),
  "_5E": Object.freeze(["Kaba Nim Hisâr"]),
  "_4E": Object.freeze(["Kaba Hisâr"]),
  "^5D": Object.freeze(["Kaba Hisâr"]),
  "_E": Object.freeze(["AşiranınYegâh", "Şorizen"]),
  "^D": Object.freeze(["AşiranınYegâh", "Şorizen"]),
  "_1E": Object.freeze(["Kaba Dik Hisâr"]),
  "^8D": Object.freeze(["Kaba Dik Hisâr"]),
  "E": Object.freeze(["Aşîrân"]),
  "F": Object.freeze(["Acem Aşîrân"]),
  "^1F": Object.freeze(["Dik Acem Aşîrân"]),
  "_8G": Object.freeze(["Dik Acem Aşîrân"]),
  "^4F": Object.freeze(["Arak"]),
  "_5G": Object.freeze(["Arak"]),
  "^5F": Object.freeze(["Geveşt"]),
  "_4G": Object.freeze(["Geveşt"]),
  "_1G": Object.freeze(["Dik Geveşt"]),
  "^8F": Object.freeze(["Dik Geveşt"]),
  "G": Object.freeze(["Rast"]),
  "^4G": Object.freeze(["Nim Zirgüle"]),
  "_5A": Object.freeze(["Nim Zirgüle"]),
  "_4A": Object.freeze(["Zirgüle"]),
  "^5G": Object.freeze(["Zirgüle"]),
  "_1A": Object.freeze(["Dik Zirgüle"]),
  "^8G": Object.freeze(["Dik Zirgüle"]),
  "A": Object.freeze(["Dügâh"]),
  "_5B": Object.freeze(["Kürdî"]),
  "^4A": Object.freeze(["Kürdî"]),
  "_4B": Object.freeze(["Dik Kürdî", "Nihavend", "NihavendiDügah"]),
  "^5A": Object.freeze(["Dik Kürdî", "Nihavend", "NihavendiDügah"]),
  "_1B": Object.freeze(["Segâh"]),
  "^8A": Object.freeze(["Segâh"]),
  "B": Object.freeze(["Bûselik"]),
  "_1c": Object.freeze(["Dik Bûselik"]),
  "^8b": Object.freeze(["Dik Bûselik"]),
  "c": Object.freeze(["Çârgâh"]),
  "^4c": Object.freeze(["Nim Hicâz", "Saba"]),
  "_5d": Object.freeze(["Nim Hicâz", "Saba"]),
  "^5c": Object.freeze(["Hicâz"]),
  "_4d": Object.freeze(["Hicâz"]),
  "_1d": Object.freeze(["Dik Hicâz"]),
  "^8c": Object.freeze(["Dik Hicâz"]),
  "d": Object.freeze(["Nevâ", "Tiz Neva"]),
  "_5e": Object.freeze(["Beyati", "Nim Hisâr"]),
  "^4d": Object.freeze(["Beyati", "Nim Hisâr"]),
  "_4e": Object.freeze(["Hisâr"]),
  "^5d": Object.freeze(["Hisâr"]),
  "_1e": Object.freeze(["Dik Hisâr"]),
  "^8d": Object.freeze(["Dik Hisâr"]),
  "e": Object.freeze(["Hüseynî"]),
  "f": Object.freeze(["Acem"]),
  "^1f": Object.freeze(["Dik Acem"]),
  "_8g": Object.freeze(["Dik Acem"]),
  "^4f": Object.freeze(["Eviç"]),
  "_5g": Object.freeze(["Eviç"]),
  "^5f": Object.freeze(["Mâhûr"]),
  "_4g": Object.freeze(["Mâhûr"]),
  "_1g": Object.freeze(["Dik Mâhûr"]),
  "^8f": Object.freeze(["Dik Mâhûr"]),
  "g": Object.freeze(["Gerdâniye"]),
  "^4g": Object.freeze(["Nim Şehnâz"]),
  "_5a": Object.freeze(["Nim Şehnâz"]),
  "_4a": Object.freeze(["Şehnâz"]),
  "^5g": Object.freeze(["Şehnâz"]),
  "_1a": Object.freeze(["Dik Şehnâz"]),
  "^8g": Object.freeze(["Dik Şehnâz"]),
  "a": Object.freeze(["Muhayyer"]),
  "_5b": Object.freeze(["Sünbüle"]),
  "^4a": Object.freeze(["Sünbüle"]),
  "_4b": Object.freeze(["Dik Sünbüle"]),
  "^5a": Object.freeze(["Dik Sünbüle"]),
  "_1b": Object.freeze(["Tîz.Segâh"]),
  "^8a": Object.freeze(["Tîz.Segâh"]),
  "b": Object.freeze(["Tîz Bûselik"]),
  "^4c'": Object.freeze(["Tîz Dik Bûselik", "Tiz Nim Hicâz"]),
  "c'": Object.freeze(["Tîz.Çârgâh"]),
  "^5c'": Object.freeze(["Tiz Hicâz"]),
  "_1d'": Object.freeze(["Tiz Dik Hicâz"]),
  "^4d'": Object.freeze(["Tiz Nim Hisâr"]),
  "_4e'": Object.freeze(["Tiz Hisâr"]),
  "_1e'": Object.freeze(["Tiz Dik Hisâr"]),
  "e'": Object.freeze(["Tiz Hüseynî"]),
  "f'": Object.freeze(["Tiz Acem"]),
  "^4f'": Object.freeze(["Tiz Eviç"]),
  "g'": Object.freeze(["Tiz Gerdâniye"]),
  "b'": Object.freeze(["Tiz Tîz Bûselik"]),
  "c''": Object.freeze(["Tiz Tîz Çârgâh"]),
});

export function resolvePerdeNamesFromAbcToken(abcToken) {
  const raw = String(abcToken || "").trim();
  if (!raw) return [];
  const token = raw.startsWith("=") ? raw.slice(1) : raw;
  const list = PERDE_NAMES_BY_ABC_TOKEN[token];
  return Array.isArray(list) ? list : [];
}

